name: Sync github repo with azure repo and update PBI workspace
on:
  push:
    branches:
      - '*' # applies for all branches in github.
      - '!master' # This line is used to restrict this pipeline which won't triggers for master branch
jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    environment: develop # mention that environment name that what we have created in step 1.
    steps:
    - uses: actions/checkout@v2
    - name: Sync repo
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSERPASSWORD: ${{secrets.AZUSERPASSWORD}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
        AZPROJECT: ${{secrets.AZPROJECT}}
        WORKSPACE_ID: ${{secrets.WORKSPACE_ID}}
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        TENANT_ID: ${{secrets.TENANT_ID}}
      run: |
         chmod +x ./sync_repo.sh
      shell: bash
    - name: Update workspace
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: ${{secrets.AZUSERNAME}}
        AZUSERPASSWORD: ${{secrets.AZUSERPASSWORD}}
        AZUSER_EMAIL: ${{secrets.AZUSER_EMAIL}}
        AZORG: ${{secrets.AZORG}}
        AZPROJECT: ${{secrets.AZPROJECT}}
        WORKSPACE_ID: ${{secrets.WORKSPACE_ID}}
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        TENANT_ID: ${{secrets.TENANT_ID}}
      run: |
         chmod +x ./update_workspace.sh
      shell: bash
  